[build]
  publish = "/"
  functions = "netlify/functions"

# /admin should load the admin index
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200

# Proxy /content/* to your UpCloud bucket's content/ folder
[[redirects]]
  from = "/content/*"
  to   = "https://jii3i.upcloudobjects.com/korndog-media/content/:splat"
  status = 200
  force = true
