
[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/collectables"
  to = "/collectables/"
  status = 301
